do
msgbox"31"
msgbox"napıyon la"
msgbox"ahahahah bilgisayarın benim"
msgbox"APTAL"
msgbox"mal"
msgbox"SENİ UYARMIŞTIM"
msgbox"msgbox ile yapılmıştır"
msgbox"ne bakıyon la"
msgbox"KIRMIZI BÖLGEEEEE"
msgbox"HHAHAHAHAH"
msgbox"ulennnnn"
msgbox"uleeeee"
msgbox"keşke memz i yapa bilsem..."
msgbox"by karpuz"
msgbox"bu virüsü karpuz yaptı"
msgbox"amk"
msgbox"TOST"
msgbox"@karpuz_savaşçısı"
msgbox"ne bakıyon  amk"
msgbox"AAAAAA BENDE ŞAŞIRDIM YENİ PCM OLDU YAY"
msgbox"START"
msgbox"başla ulee"
msgbox"TOST SEVERÜM"
msgbox"12345 şifre"
msgbox"1234567890"
msgbox"chatgpt 31 xxxx"
msgbox"xxx sokucu xxx"
msgbox"pro sun ayn 100/100 real"
msgbox"hile bumu pcyi siliyo..."
msgbox"0%00%0100/2"
msgbox"aahhahahahha"
msgbox"ponkao ya selam mım var ;D"
msgbox"ka BUMMMMMMMMMM!"
msgbox"boş"
msgbox""
msgbox"5555555555"
msgbox"!!!!!!!!!"
msgbox"? korktunmu"
msgbox"masa"
msgbox"galiba bu çökertici"
msgbox"keşke memz i yapa bilsem..."
msgbox"ahahahah bilgisayarın benim"
msgbox"0%00%0100/231"
msgbox"31 şakası ;D"
msgbox"Aop785999"
msgbox"UYARI PCNİZ CPU KEMİRİYOR"
msgbox"ulen pcn güzel miş miş çilerine"
msgbox"ulennnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn"
msgbox"EN BÜYÜK YAZIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"
msgbox"ııııııııı"
msgbox"iiiii osurdun mu sanki"
msgbox"gi bi gibi"
msgbox"piskolajin bozuldu demi çnkü karpuz yemedin"
msgbox"karpuz"
msgbox"nam nam karpiz"
msgbox"UYARI PCNİZ CPU KEMİRİYOR"
msgbox"UYARI PCNİZ CPU KEMİRİYOR"
msgbox"UYARI PCNİZ CPU KEMİRİYOR"
msgbox"UYARI PCNİZ CPU KEMİRİYOR"
msgbox"UYARI PCNİZ CPU KEMİRİYOR"
msgbox"UYARI PCNİZ CPU KEMİRİYOR"
msgbox"UYARI PCNİZ CPU KEMİRİYOR"
msgbox"UYARI PCNİZ CPU KEMİRİYOR"
msgbox"UYARI PCNİZ CPU KEMİRİYOR"
msgbox"UYARI PCNİZ CPU KEMİRİYOR"
msgbox"UYARI PCNİZ CPU KEMİRİYOR"
msgbox"UYARI PCNİZ CPU KEMİRİYOR"
msgbox"UYARI BELLEK GG"
msgbox"ne bakıyon tırrek"
msgbox"50 kuruşun varmı..."
msgbox"çalıştırmasaydın keşke"
msgbox"ne bakıyo n amk anti virüssü açsaydın"
msgbox"zor kodlama"
msgbox"ahbe"
msgbox"BELKİ SENİ KEYLOGGER DEN KURTARDIM"
msgbox"BELKİ SENİ MEMZ DEN KURTARDIM"
msgbox"BELKİ SENİ SALİNAWİN DEN KURTARDIM"
msgbox"BELKİ SENİ TROJAN DEN KURTARDIM"
msgbox"21"
msgbox"65"
msgbox"1"
msgbox"2"
msgbox"3"
msgbox"msgbox"
msgbox"do loop bu kadarrrrr"
msgbox"çökerttimmi harbi"
msgbox"31"
msgbox"ne bakıyon"
msgbox"yüzümde bişi mi var"
msgbox"ARKANA BAKMA"
msgbox"boşmusun olümmmmm"
msgbox"öl"
msgbox"kardaşımmmmm"
msgbox"ne bakıyon ponkazo"
msgbox"son 2"
msgbox"belki tek bunu görüyon ama arkada 100000000000 tane kod çalışıyo..."
loop